shared:
  node_container: &node_container
    language: node_js
    node_js:
      - 10.14.0
    before_install:
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
      - export PATH="$HOME/.yarn/bin:$PATH"
    install:
      - yarn install --production=false --frozen-lockfile
    cache: yarn

matrix:
  include:
    - <<: *node_container
      name: 'Build assets'
      script:
        - yarn build
